### ISSUE TITLE
Incorrectly states Nvidia 710 is not Windows 11 Compatible

### ISSUE THREAD

**Issue by jamieolney** [ByteJammer/Win11RCT#3]
Microsoft & Nvidia have confirmed that a Nvidia GT710 and all Kepler GPUs are Windows 11 Compliant. 
https://uk.download.nvidia.com/Windows/472.12/472.12-win11-win10-win8-win7-release-notes.pdf

The GPUs need to support DX 12 but can still be feature level 11.1. 

Running this tool on my PC suggests not complaint - but Windows Update itself says it is and coming soon

**Comment by ByteJammer** [comment]
On which version of Windows are you running the tool and are your Nvidia drivers up to date?
